seed_everything: true
model:
  class_path: src.models.GATModel
  init_args:
    in_channels: 20
    num_layers: 2
    hidden_channels: 32
    heads: 2
    out_channels: 1
    dropout: 0.01
    jk: last
    v2: true
data:
  class_path: src.dataloader.ProteinGraphDataModule
  init_args:
    root: ./
    columns:
      - chain_id
      - coords
      - edge_index
      - kind
      - node_id
      - residue_number
      - meiler
      - amino_acid_one_hot
    batch_size: 32
    num_workers: 4
# optimizer:
#   class_path: torch.optim.Adam
#   init_args:
#     lr: 0.001
#     weight_decay: 0.0001
trainer:
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: gat
        log_graph: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
    - class_path: source.callbacks.LogParametersCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: val_loss
        mode: min
        filename: "{epoch:02d}-{val_loss:.2f}"
  enable_progress_bar: true
  max_epochs: -1
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32